//! # r23-replay — Round 23 R1 continuous prequential scored replay driver
//!
//! Implements the **R1** phase of the Round 23 plan (sections 5.1, 5.2, 5.3).
//!
//! ## What this crate does
//!
//! R1's rule (plan §5): *"signal/fit may be generated by Python, but the scored
//! PnL must be produced by the same production-conservative Rust runtime."* The
//! Round 22 audit found the scored PnL was a pure-Python engine that skipped
//! filters, margin, maintenance, partial-fill, leg-delay, reject, funding and
//! traces. This crate fixes that by routing every replay through
//! [`backtest_engine::martingale::sync_cycle_engine::run_synchronized_cycle_replay`],
//! whose FO/SO emit sites already call the production-conservative gates
//! (`filter_order_conservative`, `check_liquidation_buffer`,
//! `apply_partial_fill`, `next_so_close_maintenance_reserve_ok`). So the
//! conservative accounting is not re-implemented here — it is reused.
//!
//! ## Continuous 12-block protocol
//!
//! The plan (§6) requires one continuous cash/margin/equity account across
//! `tb01..tb12`. The sync cycle engine runs as a single call over a merged bar
//! stream; calling it once per block would reset cycle state between blocks.
//! Therefore the driver offers two fidelity levels:
//!
//! - [`ReplayMode::ContinuousMerged`] — merge all 12 blocks' test bars into one
//!   sorted stream and call the engine ONCE. This preserves full inter-block
//!   cycle/equity continuity and is the production-faithful path. The frozen
//!   fit per group is taken from the fit computed on `[fit_start, tb01_start -
//!   purge]` (the earliest, strictest fit window); the engine never re-fits.
//! - [`ReplayMode::BlockWiseCarry`] — call the engine once per block, carrying
//!   the settled equity forward as the next block's budget (cycle state resets
//!   between blocks but the account balance is continuous). This mode exists to
//!   exercise per-block fit refit and is used by the directed tests.
//!
//! ## Registry contract
//!
//! Every replay writes exactly one `Running` and one `Terminal` row via
//! [`r23_registry::Launcher`]. Non-complete outcomes atomically write a paired
//! failure-ledger row (§4.3 canary #15). The terminal row carries the eight
//! trace SHA-256 digests extracted from the engine's `SYNC_SUMMARY` JSON.
//!
//! ## Post-replay accounting invariants (§5.1)
//!
//! After the engine returns, the driver asserts the §5.1 invariants that are
//! checkable from the result: no liquidation (`metrics.liquidation_count == 0`),
//! equity never `<= 0`, and (when the engine emits them) the trace hashes are
//! non-empty. A breach forces a `FailedExecution` terminal with a failure row.

pub mod account;
pub mod continuous;
pub mod fit;
pub mod g1_harness;
pub mod g2_stress;
pub mod gated_martin;
pub mod m1_signal;
pub mod m2_signal;
pub mod multiple_testing;
pub mod summary;
pub mod directed_checks;
pub mod xs_momentum;

pub use account::{ContinuousAccount, AccountSnapshot};
pub use continuous::{
    run_continuous_replay, BlockReplayInput, ReplayMode, ContinuousReplayConfig, ReplayOutcome,
};
pub use summary::{extract_trace_hashes, TraceHashes, SyncSummary};
